### ISSUE TITLE
在mac上使用插件,生成的配置文件路径有误

### ISSUE THREAD

**Issue by No-Github** [fKzhangsa/FilterJs#3]
加载后 log如下
<img width="932" alt="image" src="https://github.com/fKzhangsa/FilterJs/assets/18167071/553a98bb-9afb-40b9-97ca-1f96c47c827a">

访问这个tmp路径

<img width="728" alt="image" src="https://github.com/fKzhangsa/FilterJs/assets/18167071/063f59b4-5383-4cfc-b607-531779821e31">

不存在这个Config.txt
上级路径也没有
<img width="713" alt="image" src="https://github.com/fKzhangsa/FilterJs/assets/18167071/73938bc9-1fff-466f-81b5-2560831bd8f5">

**Comment by fKzhangsa** [comment]
感谢你的反馈，但是我在mac上测试了下并没有出现Config文件丢失的问题。你可以尝试删除整个YitaiqiJSFilter文件，让程序再重新生成一遍。看看是否可以解决你遇到的问题。

**Comment by No-Github** [comment]
<img width="710" alt="image" src="https://github.com/fKzhangsa/FilterJs/assets/18167071/e3036beb-caae-4920-a447-d4de26260e21">

可以了,重新加载后出现了
