### ISSUE TITLE
可以加一个匹配所有参数的功能吗

### ISSUE THREAD

**Issue by rechallage** [fKzhangsa/FilterJs#6]
就是匹配返回包所有参数，通过搜索框搜索子域名把该域名下的参数整合到一个列表

**Comment by fKzhangsa** [comment]
返回包中的参数指的是什么，如果有图例说明就好了。

**Comment by rechallage** [comment]
![image](https://github.com/fKzhangsa/FilterJs/assets/85208463/9891e6c5-0653-4102-bd4f-5398fcb60285)
谢谢大佬回复，就是类似于这种的js代码，或者请求包用到的参数也记录下来
![image](https://github.com/fKzhangsa/FilterJs/assets/85208463/d5d91561-4e16-4ecc-9604-10c5c334d5df)

**Comment by fKzhangsa** [comment]
非常感谢你提供的建议，但很抱歉，据我的了解，从js或html页面提取参数会导致参数误报率太高了，也很难和对应的接口关联到一起。 至于提取请求的参数出来这个功能我觉得应该放到另一个插件实现比较合适，毕竟这个插件还是应该精简一些，正如它的名字一样JSFilter。

**Comment by rechallage** [comment]
谢谢大佬的答复，确实这种精确的参数匹配难度太大，只能肉眼判断。之前接口测试需要才想到这些js文件存在的参数进行fuzz不过太繁琐了，还是感谢你的解惑。

**Comment by fKzhangsa** [comment]
没关系。
